server:
  port: 9000
spring:
  application:
    name: client-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: client-service
            client-secret: 3MFB9rSv9fqR23lZYf2MOhAL4U5HiIbM
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:7080/realms/master/protocol/openid-connect/token


logging:
  level:
    org:
      springframework:
        security=DEBUG: